/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    put: operations['createOrReplaceTemplate']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{id}/document': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RO
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RW
     */
    post: operations['generateDocumentFromTemplate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/variables': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    get: operations['getTemplateVariables']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/templates/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RO
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RW
     */
    get: operations['getTemplate']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    get: operations['getTemplateGroups']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/groups/{groupCode}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RO
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION__RW
     */
    get: operations['getTemplatesForGroup']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    TemplateRequest: {
      /** Format: uuid */
      id?: string
      code: string
      name: string
      description?: string
      instructionText?: string
      variables: components['schemas']['TemplateRequest.Variable'][]
      groups: components['schemas']['TemplateRequest.Group'][]
    }
    'TemplateRequest.Group': {
      code: string
    }
    'TemplateRequest.Variable': {
      code: string
      required: boolean
    }
    TemplateResponse: {
      /** Format: uuid */
      id: string
    }
    GenerateFromTemplate: {
      filename: string
      variables: {
        [key: string]: unknown
      }
    }
    TemplateVariables: {
      domains: components['schemas']['TemplateVariables.Domain'][]
    }
    'TemplateVariables.Domain': {
      code: string
      description: string
      variables: components['schemas']['TemplateVariables.Variable'][]
    }
    'TemplateVariables.Variable': {
      code: string
      description: string
      /** @enum {string} */
      type: 'BINARY' | 'DATE' | 'NUMBER' | 'STRING' | 'TIME'
    }
    Group: {
      code: string
      name: string
      description: string
      roles: string[]
    }
    TemplateDetail: {
      /** Format: uuid */
      id: string
      code: string
      name: string
      description: string
      instructionText?: string
      groups: components['schemas']['Group'][]
      variables: components['schemas']['TemplateVariables']
    }
    TemplateGroups: {
      groups: components['schemas']['Group'][]
    }
    TemplateGroupTemplates: {
      group: components['schemas']['Group']
      templates: components['schemas']['TemplateSummary'][]
    }
    TemplateSummary: {
      /** Format: uuid */
      id: string
      code: string
      name: string
      description: string
      instructionText?: string
      variableDomains: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createOrReplaceTemplate: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          template: components['schemas']['TemplateRequest']
          /** Format: binary */
          file?: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TemplateResponse']
        }
      }
    }
  }
  generateDocumentFromTemplate: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': {
          data: components['schemas']['GenerateFromTemplate']
          /** Format: binary */
          perImage?: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
    }
  }
  getTemplateVariables: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateVariables']
        }
      }
    }
  }
  getTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateDetail']
        }
      }
    }
  }
  getTemplateGroups: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateGroups']
        }
      }
    }
  }
  getTemplatesForGroup: {
    parameters: {
      query?: never
      header?: never
      path: {
        groupCode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TemplateGroupTemplates']
        }
      }
    }
  }
}
