/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/transfers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    get: operations['retrieveTransfer']
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    put: operations['applyActions']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transfers/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    post: operations['initiateTransfer']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/search/prisons/{prisonCode}/transfers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    post: operations['findTransfersForPrison']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/transfers/{id}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    get: operations['retrieveHistory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/reference-data/{domain}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_TRANSFERS__TRANSFER_SCHEDULER_UI
     */
    get: operations['getDomain']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApplyDestination: {
      type: 'ApplyDestination'
    } & (Omit<components['schemas']['TransferAction'], 'type'> & {
      destinationCode: string
    })
    ApplyLogistics: {
      type: 'ApplyLogistics'
    } & (Omit<components['schemas']['TransferAction'], 'type'> & {
      logisticsCode?: string | null
    })
    ApplyReason: {
      type: 'ApplyReason'
    } & (Omit<components['schemas']['TransferAction'], 'type'> & {
      reasonCode: string
    })
    CancelTransfer: {
      type: 'CancelTransfer'
    } & Omit<components['schemas']['TransferAction'], 'type'>
    PlanTransfer: {
      type: 'PlanTransfer'
    } & (Omit<components['schemas']['TransferAction'], 'type'> & {
      /** Format: date */
      requestedOn: string
      priorityCode: string
      comments?: string | null
    })
    ScheduleTransfer: {
      type: 'ScheduleTransfer'
    } & (Omit<components['schemas']['TransferAction'], 'type'> & {
      /** Format: date-time */
      start: string
      comments?: string | null
    })
    TransferAction: {
      type: string
    }
    TransferActions: {
      actions: (
        | components['schemas']['ApplyDestination']
        | components['schemas']['ApplyLogistics']
        | components['schemas']['ApplyReason']
        | components['schemas']['CancelTransfer']
        | components['schemas']['PlanTransfer']
        | components['schemas']['ScheduleTransfer']
      )[]
      reason?: string | null
    }
    AuditHistory: {
      content: components['schemas']['AuditedAction'][]
    }
    AuditedAction: {
      user: components['schemas']['User']
      /** Format: date-time */
      occurredAt: string
      domainEvents: string[]
      reason?: string | null
      changes: components['schemas']['Change'][]
    }
    Change: {
      propertyName: string
      previous?: (string | number | boolean) | null
      change?: (string | number | boolean) | null
    }
    User: {
      username: string
      name: string
    }
    CreatePlanRequest: {
      /** Format: date */
      requestedOn: string
      priorityCode: string
      comments?: string | null
    }
    CreateScheduleRequest: {
      /** Format: date-time */
      start: string
      comments?: string | null
    }
    CreateTransferRequest: {
      reasonCode: string
      destinationCode?: string | null
      logisticsCode?: string | null
      plan?: components['schemas']['CreatePlanRequest'] | null
      schedule?: components['schemas']['CreateScheduleRequest'] | null
    }
    CodedDescription: {
      code: string
      description: string
    }
    Movement: {
      /** Format: date-time */
      occurredAt: string
      comments?: string | null
    }
    Person: {
      identifier: string
      firstName: string
      lastName: string
    }
    Plan: {
      /** Format: date */
      requestedOn: string
      priority: components['schemas']['CodedDescription']
      comments?: string | null
    }
    Prison: {
      code: string
      name: string
    }
    Schedule: {
      /** Format: date-time */
      start: string
      comments?: string | null
    }
    Transfer: {
      /** Format: uuid */
      id: string
      person: components['schemas']['Person']
      prison: components['schemas']['Prison']
      status: components['schemas']['CodedDescription']
      reason: components['schemas']['CodedDescription']
      destination?: components['schemas']['Prison'] | null
      logistics?: components['schemas']['CodedDescription'] | null
      plan?: components['schemas']['Plan'] | null
      schedule?: components['schemas']['Schedule'] | null
      movement?: components['schemas']['Movement'] | null
      /** @enum {string} */
      stage: 'PLANNING' | 'SCHEDULED'
    }
    TransferPrisonSearchRequest: {
      /** Format: date */
      start: string
      /** Format: date */
      end: string
      query?: string | null
      statusCodes?: (
        | 'PLANNING'
        | 'READY_TO_SCHEDULE'
        | 'SCHEDULED'
        | 'CANCELLED'
        | 'EXPIRED'
        | 'IN_TRANSIT'
        | 'COMPLETED'
      )[]
      reasonCodes?: string[]
      destinationCodes?: string[]
      logisticsCodes?: string[]
      /** @enum {string|null} */
      priorityCodes?: ('1' | '2' | '3')[]
      /** @enum {string|null} */
      stage?: 'PLANNING' | 'SCHEDULED' | null
      /** Format: int32 */
      page: number
      /** Format: int32 */
      size: number
      sort: string
    }
    PageMetadata: {
      /** Format: int64 */
      totalElements: number
    }
    TransferSearchResponse: {
      content: components['schemas']['Transfer'][]
      metadata: components['schemas']['PageMetadata']
    }
    ReferenceDataResponse: {
      domain: components['schemas']['CodedDescription']
      items: components['schemas']['CodedDescription'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  retrieveTransfer: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Transfer']
        }
      }
    }
  }
  applyActions: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferActions']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  initiateTransfer: {
    parameters: {
      query?: never
      header?: {
        /** @description Relevant caseload id for the client identity in context e.g. the active caseload id of the logged in user. */
        CaseloadId?: string
      }
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTransferRequest']
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['Transfer']
        }
      }
    }
  }
  findTransfersForPrison: {
    parameters: {
      query?: never
      header?: never
      path: {
        prisonCode: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferPrisonSearchRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TransferSearchResponse']
        }
      }
    }
  }
  retrieveHistory: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditHistory']
        }
      }
    }
  }
  getDomain: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The reference data domain required. This is case insensitive. */
        domain: 'transfer-logistics' | 'transfer-priority' | 'transfer-reason' | 'transfer-status'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReferenceDataResponse']
        }
      }
    }
  }
}
