// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type RetryDlqResult = {
  messagesFoundCount: number
}

export type PurgeQueueResult = {
  messagesFoundCount: number
}

/**
 * Error response
 */
export type ErrorResponse = {
  /**
   * HTTP status code
   */
  status: number
  /**
   * User message for the error
   */
  userMessage: string
  /**
   * More detailed error message
   */
  developerMessage: string
  /**
   * When present, uniquely identifies the type of error making it easier for clients to discriminate without relying on error description or HTTP status code; see `uk.gov.justice.digital.hmpps.hmppsnonassociationsapi.config.ErrorCode` enumeration in hmpps-non-associations-api
   */
  errorCode?: number | null
  /**
   * More information about the error
   */
  moreInfo?: string | null
}

/**
 * Request to re-open a non-association
 */
export type ReopenNonAssociationRequest = {
  /**
   * Reason for re-opening the non-association
   */
  reopenReason: string
  /**
   * Date and time of the re-open, if not provided will default to today's time
   */
  reopenedAt?: string | null
  /**
   * The username of the member of staff requesting the re-open, if not provided will use the user in the JWT access token
   */
  reopenedBy: string | null
}

/**
 * Non-association
 */
export type NonAssociation = {
  /**
   * ID of the non-association
   */
  id: number
  /**
   * Prisoner number to not associate
   */
  firstPrisonerNumber: string
  /**
   * This prisoner’s role code in the non-association
   */
  firstPrisonerRole: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * This prisoner’s role description in the non-association
   */
  firstPrisonerRoleDescription: string
  /**
   * Prisoner number to not associate
   */
  secondPrisonerNumber: string
  /**
   * Other prisoner’s role code in the non-association
   */
  secondPrisonerRole: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Other prisoner’s role description in the non-association
   */
  secondPrisonerRoleDescription: string
  /**
   * Reason code why these prisoners should be kept apart
   */
  reason: 'BULLYING' | 'GANG_RELATED' | 'ORGANISED_CRIME' | 'LEGAL_REQUEST' | 'THREAT' | 'VIOLENCE' | 'OTHER'
  /**
   * Reason description why these prisoners should be kept apart
   */
  reasonDescription: string
  /**
   * Location-based restriction code
   */
  restrictionType: 'CELL' | 'LANDING' | 'WING'
  /**
   * Location-based restriction description
   */
  restrictionTypeDescription: string
  /**
   * Explanation of why prisoners are non-associated
   */
  comment: string
  /**
   * When the non-association was created
   */
  whenCreated: string
  /**
   * When the non-association was last updated
   */
  whenUpdated: string
  /**
   * User ID of the person who last updated the non-association
   */
  updatedBy: string
  /**
   * Whether the non-association is closed or is in effect
   */
  isClosed: boolean
  /**
   * User ID of the person who closed the non-association. Only present when the non-association is closed, null for open non-associations
   */
  closedBy?: string | null
  /**
   * Reason why the non-association was closed. Only present when the non-association is closed, null for open non-associations
   */
  closedReason?: string | null
  /**
   * Date and time of when the non-association was closed. Only present when the non-association is closed, null for open non-associations
   */
  closedAt?: string | null
  isOpen: boolean
}

/**
 * Request to close a non-association
 */
export type CloseNonAssociationRequest = {
  /**
   * Reason for closing the non-association
   */
  closedReason: string
  /**
   * Date and time of the closure, if not provided will default to today's time
   */
  closedAt?: string | null
  /**
   * The username of the member of staff requesting the closure, if not provided will use the user in the JWT access token
   */
  closedBy?: string | null
}

/**
 * Request format for creating a new, open, non-association between two prisoners
 */
export type CreateNonAssociationRequest = {
  /**
   * Prisoner number to not associate
   */
  firstPrisonerNumber: string
  /**
   * This prisoner’s role in the non-association
   */
  firstPrisonerRole: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Prisoner number to not associate
   */
  secondPrisonerNumber: string
  /**
   * Other prisoner’s role in the non-association
   */
  secondPrisonerRole: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Reason why these prisoners should be kept apart
   */
  reason: 'BULLYING' | 'GANG_RELATED' | 'ORGANISED_CRIME' | 'LEGAL_REQUEST' | 'THREAT' | 'VIOLENCE' | 'OTHER'
  /**
   * Location-based restriction code
   */
  restrictionType: 'CELL' | 'LANDING' | 'WING'
  /**
   * Explanation of why prisoners are non-associated
   */
  comment: string
}

/**
 * Request to delete a non-association
 */
export type DeleteNonAssociationRequest = {
  /**
   * Reason for deleting the non-association
   */
  deletionReason: string
  /**
   * The username of the member of staff requesting the deletion
   */
  staffUserNameRequestingDeletion: string
}

/**
 * Request format for updating a non-association between two prisoners
 */
export type PatchNonAssociationRequest = {
  /**
   * This prisoner’s role in the non-association
   */
  firstPrisonerRole?: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Other prisoner’s role in the non-association
   */
  secondPrisonerRole?: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Reason why these prisoners should be kept apart
   */
  reason?: 'BULLYING' | 'GANG_RELATED' | 'ORGANISED_CRIME' | 'LEGAL_REQUEST' | 'THREAT' | 'VIOLENCE' | 'OTHER'
  /**
   * Location-based restriction code
   */
  restrictionType?: 'CELL' | 'LANDING' | 'WING'
  /**
   * Explanation of why prisoners are non-associated
   */
  comment?: string | null
}

export type Attachment = {
  /**
   * The number of the attachment which will match any corresponding reference in the content section
   */
  attachmentNumber: number
  /**
   * The name or description of the attachment which will be included in the report
   */
  name: string
  /**
   * The content type of the attachment
   */
  contentType: string
  /**
   * The url to be used to download the attachment file
   */
  url: string
  /**
   * The size of the attachment file in bytes
   */
  filesize?: number | null
  /**
   * The filename of attachment file
   */
  filename: string
  /**
   * The additional headers to use when calling the url for fetching this attachment
   */
  headers?: Array<AttachmentHeader> | null
}

export type AttachmentHeader = {
  /**
   * The name of the header
   */
  name: string
  /**
   * The value of the header
   */
  value: string
}

export type HmppsSubjectAccessRequestContent = {
  /**
   * The content of the subject access request response
   */
  content: unknown
  /**
   * The details of any attachments for the subject access request response
   */
  attachments?: Array<Attachment> | null
}

export type DlqMessage = {
  body: {
    [key: string]: unknown
  }
  messageId: string
}

export type GetDlqResult = {
  messagesFoundCount: number
  messagesReturnedCount: number
  messages: Array<DlqMessage>
}

/**
 * Other prisoner’s details for an item in a list of non-associations
 */
export type OtherPrisonerDetails = {
  /**
   * Prisoner number
   */
  prisonerNumber: string
  /**
   * Other prisoner’s role code in the non-association
   */
  role: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * Other prisoner’s role description in the non-association
   */
  roleDescription: string
  /**
   * First name
   */
  firstName: string
  /**
   * Last name
   */
  lastName: string
  /**
   * ID of the prison the prisoner is assigned to
   */
  prisonId?: string | null
  /**
   * Name of the prison the prisoner is assigned to
   */
  prisonName?: string | null
  /**
   * Cell the prisoner is assigned to
   */
  cellLocation?: string | null
}

/**
 * An item in a list of non-associations for a given prisoner
 */
export type PrisonerNonAssociation = {
  /**
   * ID of the non-association
   */
  id: number
  /**
   * This prisoner’s role code in the non-association
   */
  role: 'VICTIM' | 'PERPETRATOR' | 'NOT_RELEVANT' | 'UNKNOWN'
  /**
   * This prisoner’s role description in the non-association
   */
  roleDescription: string
  /**
   * Reason code why these prisoners should be kept apart
   */
  reason: 'BULLYING' | 'GANG_RELATED' | 'ORGANISED_CRIME' | 'LEGAL_REQUEST' | 'THREAT' | 'VIOLENCE' | 'OTHER'
  /**
   * Reason description why these prisoners should be kept apart
   */
  reasonDescription: string
  /**
   * Location-based restriction code
   */
  restrictionType: 'CELL' | 'LANDING' | 'WING'
  /**
   * Location-based restriction description
   */
  restrictionTypeDescription: string
  /**
   * Explanation of why prisoners are non-associated
   */
  comment: string
  /**
   * User ID of the person who created the non-association. NOTE: For records migrated from NOMIS/Prison API this is free text and may not be a valid User ID. Additionally, migrated records might use an internal system username. It can be an empty string
   */
  authorisedBy: string
  /**
   * When the non-association was created
   */
  whenCreated: string
  /**
   * When the non-association was last updated
   */
  whenUpdated: string
  /**
   * User ID of the person who last updated the non-association
   */
  updatedBy: string
  /**
   * Whether the non-association is closed or is in effect
   */
  isClosed: boolean
  /**
   * User ID of the person who closed the non-association. Only present when the non-association is closed, null for open non-associations
   */
  closedBy?: string | null
  /**
   * Reason why the non-association was closed. Only present when the non-association is closed, null for open non-associations
   */
  closedReason?: string | null
  /**
   * Date and time of when the non-association was closed. Only present when the non-association is closed, null for open non-associations
   */
  closedAt?: string | null
  /**
   * Details about the other person in the non-association.
   */
  otherPrisonerDetails: OtherPrisonerDetails
  isOpen: boolean
}

/**
 * List of non-associations for a given prisoner
 */
export type PrisonerNonAssociations = {
  /**
   * Prisoner number
   */
  prisonerNumber: string
  /**
   * First name
   */
  firstName: string
  /**
   * Last name
   */
  lastName: string
  /**
   * ID of the prison the prisoner is assigned to
   */
  prisonId?: string | null
  /**
   * Name of the prison the prisoner is assigned to
   */
  prisonName?: string | null
  /**
   * Cell the prisoner is assigned to
   */
  cellLocation?: string | null
  /**
   * Number of open non-associations (follows includeOtherPrisons filter)
   */
  openCount: string
  /**
   * Number of closed non-associations (follows includeOtherPrisons filter)
   */
  closedCount: string
  /**
   * Non-associations with other prisoners`
   */
  nonAssociations: Array<PrisonerNonAssociation>
}

export type PageNonAssociation = {
  totalElements?: number
  totalPages?: number
  size?: number
  content?: Array<NonAssociation>
  number?: number
  first?: boolean
  last?: boolean
  sort?: SortObject
  numberOfElements?: number
  pageable?: PageableObject
  empty?: boolean
}

export type PageableObject = {
  offset?: number
  sort?: SortObject
  pageSize?: number
  pageNumber?: number
  paged?: boolean
  unpaged?: boolean
}

export type SortObject = {
  empty?: boolean
  sorted?: boolean
  unsorted?: boolean
}

/**
 * Non-association in NOMIS/Prison API format
 */
export type LegacyNonAssociation = {
  /**
   * ID of the non-association
   */
  id: number
  /**
   * Prisoner number
   */
  offenderNo: string
  /**
   * Reason code for the non-association
   */
  reasonCode: 'BUL' | 'PER' | 'RIV' | 'VIC' | 'NOT_REL' | 'UNKNOWN'
  /**
   * Reason for the non-association
   */
  reasonDescription: string
  /**
   * The non-association type code
   */
  typeCode: 'CELL' | 'LAND' | 'WING'
  /**
   * The non-association type description
   */
  typeDescription: string
  /**
   * Date and time the non-association is effective from. In Europe/London (ISO 8601) format without timezone offset e.g. YYYY-MM-DDTHH:MM:SS.
   */
  effectiveDate: string
  /**
   * Date and time the non-association expires. In Europe/London (ISO 8601) format without timezone offset e.g. YYYY-MM-DDTHH:MM:SS.
   */
  expiryDate?: string | null
  /**
   * The person who authorised the non-association (free text).
   */
  authorisedBy?: string | null
  /**
   * Additional free text comments related to the non-association.
   */
  comments: string
  /**
   * Details about the other non-association person
   */
  offenderNonAssociation: LegacyNonAssociationOtherPrisonerDetails
}

/**
 * Details about the other non-association person in NOMIS/Prison API format
 */
export type LegacyNonAssociationOtherPrisonerDetails = {
  /**
   * Prisoner number
   */
  offenderNo: string
  /**
   * Reason code for the non-association
   */
  reasonCode: 'BUL' | 'PER' | 'RIV' | 'VIC' | 'NOT_REL' | 'UNKNOWN'
  /**
   * Reason for the non-association
   */
  reasonDescription: string
}

export type Constant = {
  code: string
  description: string
}

export type RetryDlqData = {
  body?: never
  path: {
    dlqName: string
  }
  query?: never
  url: '/queue-admin/retry-dlq/{dlqName}'
}

export type RetryDlqResponses = {
  /**
   * OK
   */
  200: RetryDlqResult
}

export type RetryDlqResponse = RetryDlqResponses[keyof RetryDlqResponses]

export type RetryAllDlqsData = {
  body?: never
  path?: never
  query?: never
  url: '/queue-admin/retry-all-dlqs'
}

export type RetryAllDlqsResponses = {
  /**
   * OK
   */
  200: Array<RetryDlqResult>
}

export type RetryAllDlqsResponse = RetryAllDlqsResponses[keyof RetryAllDlqsResponses]

export type PurgeQueueData = {
  body?: never
  path: {
    queueName: string
  }
  query?: never
  url: '/queue-admin/purge-queue/{queueName}'
}

export type PurgeQueueResponses = {
  /**
   * OK
   */
  200: PurgeQueueResult
}

export type PurgeQueueResponse = PurgeQueueResponses[keyof PurgeQueueResponses]

export type ReopenNonAssociationData = {
  body: ReopenNonAssociationRequest
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/non-associations/{id}/reopen'
}

export type ReopenNonAssociationErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the REOPEN_NON_ASSOCIATIONS role with write scope.
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type ReopenNonAssociationError = ReopenNonAssociationErrors[keyof ReopenNonAssociationErrors]

export type ReopenNonAssociationResponses = {
  /**
   * Non-association re-opened
   */
  200: NonAssociation
}

export type ReopenNonAssociationResponse = ReopenNonAssociationResponses[keyof ReopenNonAssociationResponses]

export type CloseNonAssociationData = {
  body: CloseNonAssociationRequest
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/non-associations/{id}/close'
}

export type CloseNonAssociationErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role with write scope.
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type CloseNonAssociationError = CloseNonAssociationErrors[keyof CloseNonAssociationErrors]

export type CloseNonAssociationResponses = {
  /**
   * Non-association updated and returned
   */
  200: NonAssociation
}

export type CloseNonAssociationResponse = CloseNonAssociationResponses[keyof CloseNonAssociationResponses]

export type GetNonAssociationsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Whether to include open non-associations or not
     */
    includeOpen?: boolean
    /**
     * Whether to include closed non-associations or not
     */
    includeClosed?: boolean
    /**
     * Zero-based page index (0..N)
     */
    page?: number
    /**
     * The size of the page to be returned
     */
    size?: number
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>
  }
  url: '/non-associations'
}

export type GetNonAssociationsErrors = {
  /**
   * When input parameters are not valid
   */
  400: ErrorResponse
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the READ_NON_ASSOCIATIONS role.
   */
  403: ErrorResponse
}

export type GetNonAssociationsError = GetNonAssociationsErrors[keyof GetNonAssociationsErrors]

export type GetNonAssociationsResponses = {
  /**
   * A page of non-associations are returned
   */
  200: PageNonAssociation
}

export type GetNonAssociationsResponse = GetNonAssociationsResponses[keyof GetNonAssociationsResponses]

export type CreateNonAssociationData = {
  body: CreateNonAssociationRequest
  path?: never
  query?: never
  url: '/non-associations'
}

export type CreateNonAssociationErrors = {
  /**
   * Invalid request body
   */
  400: ErrorResponse
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required privileges. Requires the NON_ASSOCIATIONS role with write scope
   */
  403: ErrorResponse
  /**
   * Some of the prisoners were not be found.
   */
  404: ErrorResponse
  /**
   * Open non-association already exists or some prisoner’s location is null.
   */
  409: ErrorResponse
}

export type CreateNonAssociationError = CreateNonAssociationErrors[keyof CreateNonAssociationErrors]

export type CreateNonAssociationResponses = {
  /**
   * Returns the created non-association
   */
  201: NonAssociation
}

export type CreateNonAssociationResponse = CreateNonAssociationResponses[keyof CreateNonAssociationResponses]

export type DeleteNonAssociationData = {
  body: DeleteNonAssociationRequest
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/non-associations/{id}/delete'
}

export type DeleteNonAssociationErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the DELETE_NON_ASSOCIATIONS role with write scope.
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type DeleteNonAssociationError = DeleteNonAssociationErrors[keyof DeleteNonAssociationErrors]

export type DeleteNonAssociationResponses = {
  /**
   * Non-association deleted
   */
  204: void
}

export type DeleteNonAssociationResponse = DeleteNonAssociationResponses[keyof DeleteNonAssociationResponses]

export type GetNonAssociationsInvolvingPrisonersData = {
  /**
   * One or more distinct prisoner numbers
   */
  body?: Array<string>
  path?: never
  query?: {
    /**
     * Whether to include open non-associations or not
     */
    includeOpen?: boolean
    /**
     * Whether to include closed non-associations or not
     */
    includeClosed?: boolean
    /**
     * When provided return only non-associations where both prisoners are in the given prison
     */
    prisonId?: string
  }
  url: '/non-associations/involving'
}

export type GetNonAssociationsInvolvingPrisonersErrors = {
  /**
   * When fewer than one distinct prisoner numbers are provided or neither open nor closed non-associations are included
   */
  400: ErrorResponse
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role
   */
  403: ErrorResponse
  /**
   * Any of the prisoners could not be found.
   */
  404: ErrorResponse
}

export type GetNonAssociationsInvolvingPrisonersError =
  GetNonAssociationsInvolvingPrisonersErrors[keyof GetNonAssociationsInvolvingPrisonersErrors]

export type GetNonAssociationsInvolvingPrisonersResponses = {
  /**
   * Returns the non-associations
   */
  200: Array<NonAssociation>
}

export type GetNonAssociationsInvolvingPrisonersResponse =
  GetNonAssociationsInvolvingPrisonersResponses[keyof GetNonAssociationsInvolvingPrisonersResponses]

export type GetNonAssociationsBetweenPrisonersData = {
  /**
   * Two or more distinct prisoner numbers
   */
  body?: Array<string>
  path?: never
  query?: {
    /**
     * Whether to include open non-associations or not
     */
    includeOpen?: boolean
    /**
     * Whether to include closed non-associations or not
     */
    includeClosed?: boolean
    /**
     * When provided return only non-associations where both prisoners are in the given prison
     */
    prisonId?: string
  }
  url: '/non-associations/between'
}

export type GetNonAssociationsBetweenPrisonersErrors = {
  /**
   * When fewer than two distinct prisoner numbers are provided or neither open nor closed non-associations are included
   */
  400: ErrorResponse
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role
   */
  403: ErrorResponse
  /**
   * Any of the prisoners could not be found.
   */
  404: ErrorResponse
}

export type GetNonAssociationsBetweenPrisonersError =
  GetNonAssociationsBetweenPrisonersErrors[keyof GetNonAssociationsBetweenPrisonersErrors]

export type GetNonAssociationsBetweenPrisonersResponses = {
  /**
   * Returns the non-associations
   */
  200: Array<NonAssociation>
}

export type GetNonAssociationsBetweenPrisonersResponse =
  GetNonAssociationsBetweenPrisonersResponses[keyof GetNonAssociationsBetweenPrisonersResponses]

export type GetNonAssociationData = {
  body?: never
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/non-associations/{id}'
}

export type GetNonAssociationErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type GetNonAssociationError = GetNonAssociationErrors[keyof GetNonAssociationErrors]

export type GetNonAssociationResponses = {
  /**
   * Returns the non-association
   */
  200: NonAssociation
}

export type GetNonAssociationResponse = GetNonAssociationResponses[keyof GetNonAssociationResponses]

export type PatchNonAssociationData = {
  body: PatchNonAssociationRequest
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/non-associations/{id}'
}

export type PatchNonAssociationErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role with write scope.
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type PatchNonAssociationError = PatchNonAssociationErrors[keyof PatchNonAssociationErrors]

export type PatchNonAssociationResponses = {
  /**
   * Non-association updated and returned
   */
  200: NonAssociation
}

export type PatchNonAssociationResponse = PatchNonAssociationResponses[keyof PatchNonAssociationResponses]

export type GetSarContentByReferenceData = {
  body?: never
  path?: never
  query?: {
    /**
     * NOMIS Prison Reference Number
     */
    prn?: string
    /**
     * nDelius Case Reference Number
     */
    crn?: string
    /**
     * Optional parameter denoting minimum date of event occurrence which should be returned in the response
     */
    fromDate?: string
    /**
     * Optional parameter denoting maximum date of event occurrence which should be returned in the response
     */
    toDate?: string
  }
  url: '/subject-access-request'
}

export type GetSarContentByReferenceErrors = {
  /**
   * The client does not have authorisation to make this request
   */
  401: ErrorResponse
  /**
   * Forbidden, requires an appropriate role
   */
  403: ErrorResponse
  /**
   * Unexpected error occurred
   */
  500: ErrorResponse
}

export type GetSarContentByReferenceError = GetSarContentByReferenceErrors[keyof GetSarContentByReferenceErrors]

export type GetSarContentByReferenceResponses = {
  /**
   * Request successfully processed - content found
   */
  200: HmppsSubjectAccessRequestContent
  /**
   * Request successfully processed - no content found
   */
  204: {
    [key: string]: unknown
  }
  /**
   * Subject Identifier is not recognised by this service
   */
  209: {
    [key: string]: unknown
  }
}

export type GetSarContentByReferenceResponse =
  GetSarContentByReferenceResponses[keyof GetSarContentByReferenceResponses]

export type GetDlqMessagesData = {
  body?: never
  path: {
    dlqName: string
  }
  query?: {
    maxMessages?: number
  }
  url: '/queue-admin/get-dlq-messages/{dlqName}'
}

export type GetDlqMessagesResponses = {
  /**
   * OK
   */
  200: GetDlqResult
}

export type GetDlqMessagesResponse = GetDlqMessagesResponses[keyof GetDlqMessagesResponses]

export type GetPrisonerNonAssociationsData = {
  body?: never
  path: {
    /**
     * The prisoner number
     */
    prisonerNumber: string
  }
  query?: {
    /**
     * Whether to include open non-associations or not
     */
    includeOpen?: boolean
    /**
     * Whether to include closed non-associations or not
     */
    includeClosed?: boolean
    /**
     * Whether to include non-associations with prisoners in other prisons
     */
    includeOtherPrisons?: boolean
    /**
     * Sort non-associations by
     */
    sortBy?:
      | 'WHEN_CREATED'
      | 'WHEN_UPDATED'
      | 'WHEN_CLOSED'
      | 'LAST_NAME'
      | 'FIRST_NAME'
      | 'PRISONER_NUMBER'
      | 'PRISON_ID'
      | 'PRISON_NAME'
      | 'CELL_LOCATION'
    /**
     * Sort direction (fallback depends on sortBy)
     */
    sortDirection?: 'ASC' | 'DESC'
  }
  url: '/prisoner/{prisonerNumber}/non-associations'
}

export type GetPrisonerNonAssociationsErrors = {
  /**
   * Bad request; for example including neither open nor closed non-associations
   */
  400: ErrorResponse
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS role
   */
  403: ErrorResponse
  /**
   * Any of the prisoners could not be found.
   */
  404: ErrorResponse
}

export type GetPrisonerNonAssociationsError = GetPrisonerNonAssociationsErrors[keyof GetPrisonerNonAssociationsErrors]

export type GetPrisonerNonAssociationsResponses = {
  /**
   * Returns non-association details for this prisoner
   */
  200: PrisonerNonAssociations
}

export type GetPrisonerNonAssociationsResponse =
  GetPrisonerNonAssociationsResponses[keyof GetPrisonerNonAssociationsResponses]

export type GetLegacyByIdData = {
  body?: never
  path: {
    /**
     * The non-association ID
     */
    id: number
  }
  query?: never
  url: '/legacy/api/non-associations/{id}'
}

export type GetLegacyByIdErrors = {
  /**
   * Unauthorized to access this endpoint
   */
  401: ErrorResponse
  /**
   * Missing required role. Requires the NON_ASSOCIATIONS_SYNC role
   */
  403: ErrorResponse
  /**
   * Non-association not found
   */
  404: ErrorResponse
}

export type GetLegacyByIdError = GetLegacyByIdErrors[keyof GetLegacyByIdErrors]

export type GetLegacyByIdResponses = {
  /**
   * Returns the non-association
   */
  200: LegacyNonAssociation
}

export type GetLegacyByIdResponse = GetLegacyByIdResponses[keyof GetLegacyByIdResponses]

export type ConstantsData = {
  body?: never
  path?: never
  query?: never
  url: '/constants'
}

export type ConstantsResponses = {
  /**
   * Returns codes and descriptions
   */
  200: {
    [key: string]: Array<Constant>
  }
}

export type ConstantsResponse = ConstantsResponses[keyof ConstantsResponses]
