---
# Per environment values which override defaults in hmpps-transfer-scheduler-ui/values.yaml

generic-service:
  ingress:
    host: transfer-scheduler.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://transfer-scheduler.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk" # used by hmpps-connect-dps-components module
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk" # used by hmpps-connect-dps-components module
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register.hmpps.service.justice.gov.uk"
    PRISON_REGISTER_CACHE_TIMEOUT: 3600
    TRANSFER_SCHEDULER_API_URL: "https://transfer-scheduler-api.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital.prison.service.justice.gov.uk"
    PRISONER_PROFILE_URL: "https://prisoner.digital.prison.service.justice.gov.uk"
    EXTERNAL_MOVEMENTS_URL: "https://external-movements.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: PRODUCTION
    AUDIT_ENABLED: "true"

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
